### PR TITLE
Fixes for javascript highlighting

### PR DESCRIPTION
**Pull request by Waqar144**
Javascript highlighting was incorrect in some places:
```
class //not italic
this // highlighted as pink and not italic
const / var / let  // not italic
console / window // not italic
super // being highlighted as 'aqua'
function // not italic
```

## Before
jshigh1

## After
jshighfix

## VSCode used for ref, VSCode SS:
vscodejshigh

-------

One inconsistency remains if we compare with VSCode. The name of the `arrowFunc` is highlighted there while it isn't being highlighted on our side.

Note: The dimmed colors in VSCode are due to the variable being unused

### CODE REVIEW

**Comment by crusoexia** [comment]
Hey @Waqar144, I searched for the "monokai" theme in VSCode extentions, there are plenty of them. Each one has some differences from another.

This color theme is mainly inspired by [sublime text](https://www.sublimetext.com/), though VSCode is good, I still want to insist on this. However, your change is actually matched *sublimetext3*'s style:

Screen Shot 2020-03-01 at 4 28 45 PM

So this change actually looks good. I just have two proposals to make it looks more like sublime:

1. Add `call s:h("jsClassFuncName",     { "fg": s:aqua })` to highlight the class function to aqua as sublime3.
2. Change the `super`'s highlight to *green* to follow sublime's style.

Your thoughts?

**Comment by Waqar144** [comment]
@crusoexia

Indeed, and I use sublimetext for comparisons mostly. It is only that sublimetext highlighting falls apart with ReactJS(maybe I didn't have the right plugin or maybe it was the ActualVim plugin messing things)

I will make the changes as requested to match the sublimetext colors.

**Comment by Waqar144** [comment]
> Add call s:h("jsClassFuncName", { "fg": s:aqua }) to highlight the class function to aqua as sublime3.

Just checked these, it is being highlighted as green 

> Change the super's highlight to green to follow sublime's style.

and this as orange in sublimetext(`v3.2.2 build 3211`) on my side (with JS).

> Your thoughts?

my ST doesn't have builtin TS support so I guess this is a bug in the ST plugin for typescript.

Even other languages have class member functions in green

**Comment by crusoexia** [comment]
@Waqar144 oh, that's caused by the flow typed in that file. Switch to another pure js file, it looks exactly as you described.

This change looks good.

**Pull request merged**
